// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ItemData } from "./../../systems/item_seller/ItemData.sol";
import { Liquidity } from "./../../systems/item_seller/Liquidity.sol";
import { ItemSellerERC20Data } from "./../tables/ItemSellerERC20.sol";

/**
 * @title IItemSeller
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IItemSeller {
  function velorumtest25__getAllItems() external view returns (ItemData[] memory);

  function velorumtest25__invest(uint256 smartObjectId, uint256 amount) external;

  function velorumtest25__giveBackInvestment(uint256 smartObjectId) external;

  function velorumtest25__collectRewards(uint256 smartObjectId) external;

  function velorumtest25__getAllInvestments() external view returns (Liquidity[] memory);

  function velorumtest25__getItemPriceData(
    uint256 smartObjectId,
    uint256 inventoryItemId
  ) external view returns (uint256, uint256, uint256);

  function velorumtest25__registerERC20Token(uint256 smartObjectId, address tokenAddress, address receiver) external;

  function velorumtest25__updateERC20Receiver(uint256 smartObjectId, address receiver) external;

  function velorumtest25__setItemPrice(
    uint256 smartObjectId,
    uint256 inventoryItemId,
    uint256 price,
    uint256 targetQuantity
  ) external;

  function velorumtest25__unsetItemPrice(uint256 smartObjectId, uint256 inventoryItemId) external;

  function velorumtest25__purchaseItem(uint256 smartObjectId, uint256 inventoryItemId, uint256 quantity) external;

  function velorumtest25__sellItem(uint256 smartObjectId, uint256 inventoryItemId, uint256 quantity) external;

  function velorumtest25__collectTokens(uint256 smartObjectId) external;

  function velorumtest25__getERC20Data(uint256 smartObjectId) external returns (ItemSellerERC20Data memory);

  function velorumtest25__getContractAddress() external returns (address);

  function velorumtest25__getQuantity(uint256 smartObjectId, uint256 inventoryItemId) external returns (uint);
}
